const SET_COURSES="SET_COURSES";
const FETCH_COURSES="FETCH_COURSES";
const SELECTED_PRODUCT ="SELECTED_courses";
const CLEAR_CLICK_DATA ="CLEAR_CLICK_DATA";
const SELECTED_DATA="SELECED_DATA";

const POST_DATA_REQUEST = "POST_DATA_REQUEST";
const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
const POST_DATA_FAILURE = "POST_DATA_FAILURE";

const GET_COURSES_REQUEST = "GET_COURSES_REQUEST";
const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
const GET_COURSES_FAILURE = "GET_COURSES_FAILURE";


export {
    SET_COURSES,
    FETCH_COURSES,
    SELECTED_PRODUCT,
    CLEAR_CLICK_DATA,   
    SELECTED_DATA,
    POST_DATA_REQUEST,
    POST_DATA_SUCCESS,
    POST_DATA_FAILURE,
    GET_COURSES_REQUEST,
    GET_COURSES_SUCCESS,
    GET_COURSES_FAILURE,
}